### ISSUE TITLE
[Todo] UI 리팩토링

### ISSUE THREAD

**Issue by Seokjun7074** [lastname-dev/share-account-bank#33]
- [ ] 토스트 제작
- [x] 모달, 토스트 적용

<br/>

### 모달 수정 리스트
- [x] 은행 영업점 페이지
- [x] 환전 페이지
- [ ] 그룹 참여 페이지
- [ ] 초대 페이지
- [x] 회원가입 페이지
